INSERT INTO ESTOQUES(NOME_ESTOQUE, QUANTIDADE_TOTAL, VALOR_TOTAL) VALUES('Estoque de Caneta', 0, '0.0');
INSERT INTO ESTOQUES(NOME_ESTOQUE, QUANTIDADE_TOTAL, VALOR_TOTAL) VALUES('Estoque de Caderno', 0, '0.0');

INSERT INTO PRODUTOS(NOME_PRODUTO, VALOR_PRODUTO, QUANTIDADE) VALUES('Caneta Azul', '3.0', 0);
INSERT INTO PRODUTOS(NOME_PRODUTO, VALOR_PRODUTO, QUANTIDADE) VALUES('Caneta Preta', '2.5', 0);